### PR TITLE
fix invalid memory address or nil pointer dereference in baseClient.initConn

### LINKED ISSUE #3675: invalid memory address or nil pointer dereference in `*baseClient.initConn`
Hello.

There seems to be a mistake in `*baseClient.initConn()`.
The following code panics:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/redis/go-redis/v9"
)

func main() {
	rdb := redis.NewClient(&redis.Options{})
	defer rdb.Close()

	rdb.Options().MaintNotificationsConfig = nil

	resp := rdb.Publish(context.Background(), "test", "test")
	result, err := resp.Result()
	if err != nil {
		rdb.Close()
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Println(result)
}
```

`*client.Options()` clearly states that the returned value should be treated as read-only and the above panic seems to be impossible to trigger through normal means without modifying `*redis.Options`.

However, if we take a look at the code of `*baseClient.initConn()`, we can see that, on [line 538](https://github.com/redis/go-redis/blob/2b8d05ed37b37b346b72e3a642ea33a726c742b3/redis.go#L538), the method expects a `nil` `MaintNotificationsConfig`. But there is no such check on [line 540](https://github.com/redis/go-redis/blob/2b8d05ed37b37b346b72e3a642ea33a726c742b3/redis.go#L540), where the `EndpointType` field is accessed, causing the above panic.

Considering the check right before that, this does not appear to be intentional behavior.

This panic also leaves the read lock on `optLock` mutex, and the following example deadlocks:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/redis/go-redis/v9"
	"github.com/redis/go-redis/v9/maintnotifications"
)

func main() {
	rdb := redis.NewClient(&redis.Options{})
	defer rdb.Close()

	rdb.Options().MaintNotificationsConfig = nil

	defer func() {
		if r := recover(); r != nil {
			rdb.Options().MaintNotificationsConfig = maintnotifications.DefaultConfig()
			_ = rdb.Publish(context.Background(), "test", "test")
		}
	}()

	resp := rdb.Publish(context.Background(), "test", "test")
	result, err := resp.Result()
	if err != nil {
		rdb.Close()
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Println(result)
}
```

## Expected Behavior

```
0
```

or whatever the actual number of subscribers there was.

## Current Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5f9b91]

goroutine 1 [running]:
github.com/redis/go-redis/v9.(*baseClient).initConn(0xc0000000e0, {0x785860, 0x980840}, 0xc000112000)
	github.com/redis/go-redis/v9@v9.17.2/redis.go:540 +0xd51
github.com/redis/go-redis/v9.(*baseClient)._getConn(0xc0000000e0, {0x785860, 0x980840})
	github.com/redis/go-redis/v9@v9.17.2/redis.go:293 +0x74
github.com/redis/go-redis/v9.(*baseClient).getConn(0xc0000000e0, {0x785860?, 0x980840?})
	github.com/redis/go-redis/v9@v9.17.2/redis.go:272 +0x65
github.com/redis/go-redis/v9.(*baseClient).withConn(0xc0000000e0, {0x785860, 0x980840}, 0xc0000f3d70)
	github.com/redis/go-redis/v9@v9.17.2/redis.go:645 +0x49
github.com/redis/go-redis/v9.(*baseClient)._process(0x5fb94d?, {0x785860?, 0x980840?}, {0x787618?, 0xc00007c240?}, 0xc0000c0000?)
	github.com/redis/go-redis/v9@v9.17.2/redis.go:700 +0xe7
github.com/redis/go-redis/v9.(*baseClient).process(0xc0000000e0, {0x785860, 0x980840}, {0x787618, 0xc00007c240})
	github.com/redis/go-redis/v9@v9.17.2/redis.go:669 +0x76
github.com/redis/go-redis/v9.(*hooksMixin).processHook(...)
	github.com/redis/go-redis/v9@v9.17.2/redis.go:200
github.com/redis/go-redis/v9.(*Client).Process(0xc000065e90?, {0x785860?, 0x980840?}, {0x787618, 0xc00007c240})
	github.com/redis/go-redis/v9@v9.17.2/redis.go:1120 +0x3e
github.com/redis/go-redis/v9.cmdable.Publish(...)
	github.com/redis/go-redis/v9@v9.17.2/pubsub_commands.go:18
main.main()
	example.com/redis-bug/main.go:17 +0x153
exit status 2
```

or a deadlock in the second example.

## Possible Solution

Probably something like:

```diff
diff --git a/redis.go b/redis.go
index a6a71067..9cdf988d 100644
--- a/redis.go
+++ b/redis.go
@@ -535,9 +535,13 @@ func (c *baseClient) initConn(ctx context.Context, cn *pool.Conn) error {
 
        // Enable maintnotifications if maintnotifications are configured
        c.optLock.RLock()
-       maintNotifEnabled := c.opt.MaintNotificationsConfig != nil && c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+       maintNotifEnabled := false
        protocol := c.opt.Protocol
-       endpointType := c.opt.MaintNotificationsConfig.EndpointType
+       var endpointType maintnotifications.EndpointType
+       if c.opt.MaintNotificationsConfig != nil {
+               maintNotifEnabled = c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+               endpointType = c.opt.MaintNotificationsConfig.EndpointType
+       }
        c.optLock.RUnlock()
        var maintNotifHandshakeErr error
        if maintNotifEnabled && protocol == 3 {
```

## Context

I don't think this is a big problem or anything serious since the observed behavior can currently only be achieved by modifying a read-only object.

But if the library's behavior changes in the future, this could cause a real problem.

## Environment

```
Fedora Linux 43
amd64
Redis 8.4.0
go-redis v9.17.2
go1.25.5
```

### PR DESCRIPTION
**Pull request by olde-ducke**
Resolves #3675.

Fixes nil pointer dereference and potential deadlock in `*baseClient.initConn()`.

---

> [!NOTE]
> **Low Risk**
> Low risk: adds nil-argument panics to client constructors and updates `Options()` docs; behavior only changes for previously invalid `nil` inputs and for callers mutating returned option pointers.
> 
> **Overview**
> Adds explicit `nil` option guards (panic with clear message) to `NewClusterClient` and documents the same expectation across `NewClient`, `NewRing`, `NewFailoverClient`, `NewFailoverClusterClient`, `NewSentinelClient`, and `NewUniversalClient`.
> 
> Clarifies that `Client.Options()`, `ClusterClient.Options()`, and `Ring.Options()` return read-only option pointers and that mutating the returned structs may cause undefined behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3694c0771aa5903e5b3af53d4ef784f567c20d11. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by ndyakov** [comment]
Hello @olde-ducke, let's continue the discussion in the issue and we can work on merging a fix.

File: redis.go [hunk 1]
```diff
@@ -535,9 +535,13 @@ func (c *baseClient) initConn(ctx context.Context, cn *pool.Conn) error {
...
 	c.optLock.RLock()
-	maintNotifEnabled := c.opt.MaintNotificationsConfig != nil && c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+	maintNotifEnabled := false
 	protocol := c.opt.Protocol
-	endpointType := c.opt.MaintNotificationsConfig.EndpointType
+	var endpointType maintnotifications.EndpointType
+	if c.opt.MaintNotificationsConfig != nil {
+		maintNotifEnabled = c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+		endpointType = c.opt.MaintNotificationsConfig.EndpointType
+	}
```
Comment (ndyakov) [inline redis.go:569]: 👍

**Comment by olde-ducke** [comment]
Yeah, the changes I made do not defend against every possible case. So I think adding note to the doc is better.

I also kept the additional `nil` check in `NewClusterClient` from previous commits, since it is the only client that does not check whether options are `nil`. I hope this is okay.

File: redis.go [hunk 2]
```diff
@@ -548,7 +548,7 @@ func (c *baseClient) initConn(ctx context.Context, cn *pool.Conn) error {
 
 	// Enable maintnotifications if maintnotifications are configured
 	c.optLock.RLock()
-	maintNotifEnabled := c.opt.MaintNotificationsConfig != nil && c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+	maintNotifEnabled := false
```
Comment (ndyakov) [inline redis.go]: @olde-ducke what was the reason for this change here? The `mainNotifEnabled` should check the options and decide if the maintenance notifications should be enabled or not, please revert it to how it was.

File: osscluster.go [hunk 3]
```diff
@@ -1141,6 +1141,9 @@ type ClusterClient struct {
 // NewClusterClient returns a Redis Cluster client as described in
 // http://redis.io/topics/cluster-spec.
 func NewClusterClient(opt *ClusterOptions) *ClusterClient {
+	if opt == nil {
+		panic("redis: NewClusterClient nil options")
+	}
```
Comment (ndyakov) [inline osscluster.go:1152]: having panic here is ok ONLY if it is documented.

File: redis.go (hunk 2 above)
Comment (ndyakov) [reply redis.go]: p.s. I saw that this was changed on the latest merge with master, so please revert this line to check if it should be enabled and then the endpoint will be populated only if the notifications are enabled, thank you.

Comment (olde-ducke) [reply redis.go]: Hi.

Initial change in this pull request looked like this:

```diff
@@ -535,9 +535,13 @@ func (c *baseClient) initConn(ctx context.Context, cn *pool.Conn) error {
 
        // Enable maintnotifications if maintnotifications are configured
        c.optLock.RLock()
-       maintNotifEnabled := c.opt.MaintNotificationsConfig != nil && c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+       maintNotifEnabled := false
        protocol := c.opt.Protocol
-       endpointType := c.opt.MaintNotificationsConfig.EndpointType
+       var endpointType maintnotifications.EndpointType
+       if c.opt.MaintNotificationsConfig != nil {
+               maintNotifEnabled = c.opt.MaintNotificationsConfig.Mode != maintnotifications.ModeDisabled
+               endpointType = c.opt.MaintNotificationsConfig.EndpointType
+       }
        c.optLock.RUnlock()
        var maintNotifHandshakeErr error
        if maintNotifEnabled && protocol == 3 {
```

This was made back in January before #3707 which is already merged, and leftover change no longer makes sense merged with main as is.

Reverted leftover line.

File: osscluster.go (hunk 3 above)
Comment (olde-ducke) [reply osscluster.go:1152]: Added additional comment for `NewClusterClient` and all clients that do the same check.
