### PR TITLE
fix(conn): conn to have state machine

### LINKED ISSUE #3582: Connection pool issues after upgrading to v9.16.0
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

We upgraded from v9.14.1 to v9.16.0, and we started observing recurrent `conn[15] rejected by hook, returning to pool` and `was not able to get a healthy connection after 3 attempts` logs. Once these logs start, we observe the `db.client.connections.use.time.milliseconds.bucket` increases significantly and stays high until we restart our service.

## Expected Behavior

We expect the `db.client.connections.use.time.milliseconds.bucket` to stay stable and the redis connection pool issues to self-resolve without needing to restart the service.

## Current Behavior

A few hours after deploying the upgraded service from version v9.14.1 to v9.16.0, we observed a significant increase in the `db.client.connections.use.time.milliseconds.bucket` metric. Specifically, the 99th percentile latency jumped from approximately 5ms to 10,000ms.

The service was deployed to our development environment last Friday, and we restarted it on Monday upon noticing the issue. The problem became apparent when our event processing began falling behind. During event handling, the service interacts with Redis.

Not sure if it's the same issue as https://github.com/redis/go-redis/issues/3571, since we observed an impact on the `db.client.connections.use.time.milliseconds.bucket` and our service functionality.

Image
Logs:

```
redis: 2025/11/01 07:07:58 pool.go:481: redis: connection pool: conn[18] rejected by hook, returning to pool
redis: 2025/11/01 07:07:58 pool.go:481: redis: connection pool: conn[18] rejected by hook, returning to pool
redis: 2025/11/01 07:07:59 pool.go:481: redis: connection pool: conn[26] rejected by hook, returning to pool
redis: 2025/11/01 07:08:00 pool.go:481: redis: connection pool: conn[32] rejected by hook, returning to pool
redis: 2025/11/01 07:08:00 pool.go:481: redis: connection pool: conn[32] rejected by hook, returning to pool
redis: 2025/11/01 07:08:01 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 07:08:14 pool.go:481: redis: connection pool: conn[36] rejected by hook, returning to pool
redis: 2025/11/01 07:15:01 pool.go:481: redis: connection pool: conn[29] rejected by hook, returning to pool
redis: 2025/11/01 07:15:01 pool.go:481: redis: connection pool: conn[29] rejected by hook, returning to pool
redis: 2025/11/01 07:15:01 pool.go:608: redis: connection pool: failed to get a usable connection after 2 attempts
redis: 2025/11/01 11:17:45 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 14:19:57 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 14:19:57 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 15:48:07 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 18:48:49 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/01 22:15:57 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 00:11:20 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 00:45:41 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 07:48:02 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 15:06:24 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 16:46:05 pool.go:481: redis: connection pool: conn[138] rejected by hook, returning to pool
redis: 2025/11/02 16:47:10 pool.go:481: redis: connection pool: conn[134] rejected by hook, returning to pool
redis: 2025/11/02 17:18:07 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 22:17:01 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/02 23:47:50 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 00:48:29 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 02:48:00 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 05:48:29 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 07:48:59 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 09:45:53 pool.go:481: redis: connection pool: conn[200] rejected by hook, returning to pool
redis: 2025/11/03 09:45:53 pool.go:481: redis: connection pool: conn[201] rejected by hook, returning to pool
redis: 2025/11/03 09:45:53 pool.go:481: redis: connection pool: conn[201] rejected by hook, returning to pool
redis: 2025/11/03 09:45:53 pool.go:481: redis: connection pool: conn[198] rejected by hook, returning to pool
redis: 2025/11/03 10:00:39 pool.go:481: redis: connection pool: conn[197] rejected by hook, returning to pool
redis: 2025/11/03 10:48:33 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 13:50:05 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
redis: 2025/11/03 11:47:28 pool.go:449: redis: connection pool: was not able to get a healthy connection after 3 attempts
```

After the restart, once again after a few hours, we observed the same issue.
Image

## Steps to Reproduce

The issue started occurring after upgrading from v9.14.1 to v9.16.0, we're not sure if there is an issue with our configuration. We did not observe this issue when we were using v9.14.0 or v9.14.1.

Here is a sample of our redis config (same as we had in https://github.com/redis/go-redis/issues/3542)
```go
type RedisConfig struct {
	Host          string
	Port          int
}

func NewRedisClient(redisConfig RedisConfig) (redis.UniversalClient, error) {
	address := fmt.Sprintf("%s:%d", redisConfig.Host, redisConfig.Port)

	provider, err := entraid.NewDefaultAzureCredentialsProvider(entraid.DefaultAzureCredentialsProviderOptions{
		DefaultAzureIdentityProviderOptions: identity.DefaultAzureIdentityProviderOptions{
			Scopes: []string{"https://redis.azure.com/.default"},
		},
	})
	if err != nil {
		return nil, err
	}

	opt := &redis.ClusterOptions{
		Addrs:                        []string{address},
		StreamingCredentialsProvider: provider,
		TLSConfig: &tls.Config{
			ServerName: redisConfig.Host,
			MinVersion: tls.VersionTLS12,
		},
	}

	client := redis.NewClusterClient(opt)

	if err := redisotel.InstrumentTracing(client); err != nil {
		return nil, err
	}

	if err := redisotel.InstrumentMetrics(client); err != nil {
		return nil, err
	}

	return client, nil
}
```

## Context (Environment)

go 1.25.3
go-redis/v9 v9.16.0
go-redis/extra/redisotel/v9 v9.16.0
go-redis-entraid v1.0.6

Our service is deployed on AKS with three active instances running concurrently. We are using Azure Managed Redis and Managed identities for auth.

### LINKED ISSUE #3593: Misleading error log in pool dialConn if DialerRetryTimeout reached
## Expected Behavior
This message in log should contain real number of dial attempts 
```
 internal.Logger.Printf(ctx, "redis: connection pool: failed to dial after %d attempts: %v", maxRetries, lastErr)
```

## Current Behavior
Error message uses maxRetries instead of real number of attempts made 
If dial attempts take too long and DialerRetryTimeout is reached before attempts number reaches DialerRetries error message is wrong.

## Possible Solution
- move loop variable `attempt` outside os loop and use in in error log 

## Steps to Reproduce
will provide on a weekend if it is needed

## Context (Environment)
This is log from my service is development environment. Dial timeout was too high so only one dial attemt was made.
Before I enabled debug log I was a little worried that service really spent 5 seconds in dialConn
```
2025-11-10T17:09:06.728221+00:00 qa myservice[48031]: 17:09:06.728154 debug: redis: dial <ip1>:6379(tcp) in 1.001085613s with dial tcp <ip1>:6379: i/o timeout
2025-11-10T17:09:06.728247+00:00 qa myservice[48031]: 17:09:06.728189 redis: connection pool: failed to dial after 5 attempts: dial tcp <ip1>:6379: i/o timeout
```

### PR DESCRIPTION
**Pull request by ndyakov**
- Add connection state tracking instead of multiple flags
- Resolve race conditions on handoff
- Improve pool performance

This PR fixes issues related to us having multiple different atomic flags in the pool connections for handoff, usability, etc. Since I tried to slightly changed the get and set operations of the pool, this correctness (which negatively impacted the performance in the first place) does not have real world drawbacks and improves developer experience. 

Also fixes:
- fixes #3593
- fixes #3582

### CODE REVIEW

File: internal/pool/conn_state.go [hunk 1]
```diff
@@ -0,0 +1,281 @@
...
+				// This prevents race condition where another thread changes state
+				// between our check and our transition
+				if sm.state.CompareAndSwap(uint32(currentState), uint32(w.targetState)) {
+					// Successfully transitioned - notify waiter
+					w.done <- nil
+					processed = true
+					break
+				} else {
+					// State changed - re-add waiter to front of queue and retry
+					sm.waiters.PushFront(w)
```
[the remark this answers is not in the document]
Comment (ndyakov) [reply internal/pool/conn_state.go]: actually, we would like to push it to the front, so it is the first one notified for the change.

File: internal/auth/streaming/pool_hook.go [hunk 2]
```diff
@@ -176,44 +171,30 @@ func (r *ReAuthPoolHook) OnPut(_ context.Context, conn *pool.Conn) (bool, bool,
...
-						}
-					}
-					if !acquired {
-						// Exponential backoff: 10, 20, 40, 80... up to 5120 microseconds
-						delay := baseDelay * time.Duration(1<<uint(attempt%10)) // Cap exponential growth
-						time.Sleep(delay)
-						attempt++
-					}
-				}
+			_, err := stateMachine.AwaitAndTransition(ctx, []pool.ConnState{pool.StateIdle}, pool.StateUnusable)
```
Comment (htemelski-oss) [inline internal/auth/streaming/pool_hook.go]: Can we preallocate this case too?

File: internal/pool/conn.go [hunk 3]
```diff
@@ -176,51 +206,134 @@ func (cn *Conn) SetUsedAt(tm time.Time) {
...
+	if old == new {
+		return true
+	}
+
+	// Transition based on new value
+	if new {
+		// Trying to make usable - transition from UNUSABLE to IDLE
+		// This should only work from UNUSABLE or INITIALIZING states
+		_, err := cn.stateMachine.TryTransition(
+			[]ConnState{StateInitializing, StateUnusable},
```
Comment (htemelski-oss) [inline internal/pool/conn.go]: Same as above, can we preallocate?

File: internal/pool/conn.go [hunk 4]
```diff
@@ -176,51 +206,134 @@ func (cn *Conn) SetUsedAt(tm time.Time) {
...
+			StateIdle,
+		)
+		return err == nil
+	} else {
+		// Trying to make unusable - transition from IDLE to UNUSABLE
+		// This is typically for acquiring the connection for background operations
+		_, err := cn.stateMachine.TryTransition(
+			[]ConnState{StateIdle},
```
Comment (htemelski-oss) [inline internal/pool/conn.go]: -||-

File: internal/pool/conn.go [hunk 5]
```diff
@@ -477,152 +596,182 @@ func (cn *Conn) GetNetConn() net.Conn {
...
+	// which should be set during handoff. If it is not set, use a 5 second default
+	deadline, ok := ctx.Deadline()
+	if !ok {
+		deadline = time.Now().Add(cn.getEffectiveReadTimeout(5 * time.Second))
+	}
+	waitCtx, cancel := context.WithDeadline(ctx, deadline)
+	defer cancel()
+	finalState, err := cn.stateMachine.AwaitAndTransition(
+		waitCtx,
+		[]ConnState{StateCreated, StateIdle, StateUnusable},
```
Comment (htemelski-oss) [inline internal/pool/conn.go]: -||-

File: internal/auth/streaming/pool_hook.go (hunk 2 above)
Comment (ndyakov) [reply internal/auth/streaming/pool_hook.go]: resolved

File: internal/pool/conn.go (hunk 3 above)
Comment (ndyakov) [reply internal/pool/conn.go]: resolved

File: internal/pool/conn.go (hunk 4 above)
Comment (ndyakov) [reply internal/pool/conn.go]: resolved

File: internal/pool/conn.go (hunk 5 above)
Comment (ndyakov) [reply internal/pool/conn.go]: resolved

File: internal/semaphore.go [hunk 6]
```diff
@@ -0,0 +1,270 @@
...
+		s.Release()
+		return ctx.Err()
+	case <-w.ready:
+		// We were notified and got the token
+		// Stop the timer and drain it if it already fired
+		if !timer.Stop() {
+			<-timer.C
+		}
+		// We have the token, just return
+		return nil
```
[the remark this answers is not in the document]
Comment (ndyakov) [reply internal/semaphore.go]: we are not holding the lock at line 173

File: internal/pool/conn.go [hunk 7]
```diff
@@ -176,51 +215,136 @@ func (cn *Conn) SetUsedAt(tm time.Time) {
...
+	// Check if current state matches the "old" usable value
+	currentUsable := (currentState == StateIdle || currentState == StateInUse)
+	if currentUsable != old {
+		return false
+	}
+
+	// If we're trying to set to the same value, succeed immediately
+	if old == new {
+		return true
+	}
```
Comment (htemelski-oss) [inline internal/pool/conn.go:212]: Should we move this to the top of the function?

File: internal/pool/conn.go [hunk 8]
```diff
@@ -176,51 +215,136 @@ func (cn *Conn) SetUsedAt(tm time.Time) {
...
+	if new {
+		// Trying to make usable - transition from UNUSABLE to IDLE
+		// This should only work from UNUSABLE or INITIALIZING states
+		// Use predefined slice to avoid allocation
+		_, err := cn.stateMachine.TryTransition(
+			validFromInitializingOrUnusable,
+			StateIdle,
+		)
+		return err == nil
+	} else {
```
Comment (htemelski-oss) [inline internal/pool/conn.go]: I guess we can remove the else

Comment (ndyakov) [reply internal/pool/conn.go]: addressed

File: maintnotifications/handoff_worker.go [hunk 9]
```diff
@@ -228,16 +226,24 @@ func (hwm *handoffWorkerManager) processHandoffRequest(request HandoffRequest) {
...
 				if err := hwm.queueHandoff(request.Conn); err != nil {
 					if internal.LogLevel.WarnOrAbove() {
 						internal.Logger.Printf(context.Background(), logs.CannotQueueHandoffForRetry(err))
 					}
+					// Failed to queue retry - remove from pending and close connection
+					hwm.pending.Delete(request.Conn.GetID())
 					hwm.closeConnFromRequest(context.Background(), request, err)
+				} else {
+					// Successfully queued retry - remove from pending (will be re-added by queueHandoff)
+					hwm.pending.Delete(request.Conn.GetID())
```
[the remark this answers is not in the document]
Comment (ndyakov) [reply maintnotifications/handoff_worker.go:240]: i think this makes it more clear what is happening.
