### PR TITLE
fix(pool): fix wantConnQueue zombie elements and add comprehensive test coverage

### LINKED ISSUE #3678: Memory leak in v9.17.2 with high concurrency - massive queuedNewConn and context object accumulation
## Description

We discovered a severe memory leak in go-redis v9.17.2 when running in high-concurrency production environments with Redis Cluster. The issue manifests as massive accumulation of `queuedNewConn` and context-related objects, leading to significant memory growth over time.

**Downgrading to v9.14.1 completely resolves the issue.**

## Environment

- **go-redis version**: v9.17.2 (problem), v9.14.1 (works fine)
- **Go version**: 1.25.5
- **Redis setup**: Redis Cluster (~600 nodes)
- **Workload**: 200 concurrent goroutines, each performing HMGet operations
- **Connection pool config**:
  PoolSize:        100
  MinIdleConns:    10
  ConnMaxIdleTime: 3 * time.Minute
  ConnMaxLifetime: 1 * time.Hour
  

```go
cli := redis.NewClusterClient(&redis.ClusterOptions{
	Addrs:           "xxx",
	PoolSize:        100,
	MinIdleConns:    10,
	ConnMaxIdleTime: time.Minute * 3,
	ConnMaxLifetime: time.Hour,
	DialTimeout:     time.Second * 5,
	WriteBufferSize: 1024,
	ReadBufferSize:  4096,
})
```

### With v9.17.2 (Problem Version)

Using `go tool pprof -inuse_objects` over a time period:

Top memory-consuming objects:
- queuedNewConn:             788,037 objects (44.35%)
- context.WithDeadlineCause: 538,367 objects (25.82%)
- context.(*cancelCtx).Done: 234,083 objects (7.82%)
Total objects:               2,991,746

Network connections:
ESTABLISHED connections: 11,938
Per-node connections: 11-55 (average ~20)

**Key observation**: 788,037 connection creation requests vs only 11,938 actual connections = **66:1 ratio**, indicating severe connection pool thrashing.

### With v9.14.1 (Working Version)

After downgrading to v9.14.1:

Top memory-consuming objects:
- queuedNewConn:             0 (not in top 30)
- context objects:           0 (not in top 30)
Total objects:               620,191 (79% reduction!)

Memory usage is stable and healthy.

## Request
Could the maintainers:
1. Review connection pool changes between v9.14.1 and v9.17.2
2. Check context lifecycle management in high-concurrency scenarios
3. Consider adding integration tests for cluster scenarios with 100+ concurrent operations

We're happy to provide more diagnostics or test specific patches if needed.

### PR DESCRIPTION
**Pull request by cyningsun**
## Summary

Fixes zombie `wantConn` elements accumulation in `wantConnQueue` and adds comprehensive test coverage. 

This PR fixes #3678

## Changes

- **Fix resource cleanup**: Properly remove `wantConn` from queue in panic/failure scenarios
- **Optimize concurrency**: Replace `Mutex` with `RWMutex` in `wantConn` for better read performance
- **Enhance existing tests**: Add `dialsQueue` cleanup assertions to 8 tests
- **Add zombie cleanup tests**: 4 new test cases covering:
  - High concurrency with continuous dial failures (1000 requests)
  - Request timeout + dial failure scenario
  - Intermittent failures over 5 seconds
  - Queue upper bound enforcement

### CODE REVIEW

**Comment by ndyakov** [comment]
@cyningsun thank you, i took a brief look and it looks promising, will do a proper review in the next couple of days.

**Comment by cyningsun** [comment]
@ndyakov, could you please take a first look when you have a moment?

Once you think it’s functionally sound, we can then ask @jseparator to help verify if it also addresses the memory leak issue they reported.

File: internal/pool/want_conn.go [hunk 1]
```diff
@@ -91,3 +97,19 @@ func (q *wantConnQueue) dequeue() (*wantConn, bool) {
...
+		if q.items[0].isOngoing() {
+			break
+		}
+
+		q.items = q.items[1:]
+		count++
+	}
+
+	return count
+}
```
Comment (ndyakov) [inline internal/pool/want_conn.go:115]: @cyningsun is it possible that the first wantConn object is still ongoing, but `wantConn` after it has failed for some reason / is done and we have to discard it?

Comment (cyningsun) [reply internal/pool/want_conn.go:115]: Yes, you've correctly identified that scenario. A `wantConn` later in the queue can fail while an earlier one is still ongoing.

The current design employs a **lazy cleanup strategy**: we only immediately clean the completed head of the queue, while intentionally **delaying the cleanup of completed elements in the middle**. This is a trade-off based on two factors:

1. **Performance:** Removing an element from the middle requires shifting all subsequent elements, a costly operation under lock.
2. **Cascading Cleanup:** When the head element is finally cleaned up, it **triggers a sweep that removes all consecutive completed elements behind it.**

The cost is temporary higher memory use for “zombie” elements. However, given the default 5-second `DialTimeout` and the random distribution of failures, cleanup progresses steadily, **keeping the accumulation bounded.**

Comment (ndyakov) [reply internal/pool/want_conn.go:115]: I will investigate the 2 scenario, but overall I do agree this is good approach.

**Review by ndyakov — APPROVED** [review]
@cyningsun looks good, pinged @jseparator on the issue to verify if this solves the reported issue for him.
